# Generated by Django 2.1.4 on 2020-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190812_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description_el',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_name_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manager name'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manager name'),
        ),
        migrations.AddField(
            model_name='store',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
