# Generated by Django 3.0.11 on 2020-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200921_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='line1_el',
            field=models.CharField(max_length=255, null=True, verbose_name='First line of address'),
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='line1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='First line of address'),
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='state_el',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State/County'),
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='state_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State/County'),
        ),
    ]
